apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-light
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:ykapilesh/elastic.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
