apiVersion: batch/v1
kind: Job
metadata:
  name: kibana-init
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: kibana-init
        image: curlimages/curl:8.7.1
        command:
        - sh
        - -c
        - |
          echo "Waiting for Kibana to be ready..."
          until curl -s http://kibana:5601/api/status | grep -q '"state":"green"'; do
            echo "Kibana not ready yet... retrying in 5s"
            sleep 5
          done
          echo "Kibana is up. Creating index pattern 'logs-*'"
          curl -X POST "http://kibana:5601/api/saved_objects/index-pattern/logs-*"             -H 'kbn-xsrf: true'             -H 'Content-Type: application/json'             -d '{"attributes":{"title":"logs-*","timeFieldName":"@timestamp"}}'
          echo "Setting 'logs-*' as default index"
          curl -X POST "http://kibana:5601/api/kibana/settings/defaultIndex"             -H 'kbn-xsrf: true'             -H 'Content-Type: application/json'             -d '{"value":"logs-*"}'
