apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: elastic
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:8.12.0
        args: ["-e"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        env:
          - name: ELASTICSEARCH_HOST
            value: "http://elasticsearch.elastic.svc.cluster.local:9200"
        volumeMounts:
          - name: varlog
            mountPath: /var/log
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
