apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elastic
spec:
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 32000
  selector:
    app: elasticsearch
