apiVersion: v1
kind: Service
metadata:
  name: filebeat
  namespace: logging
spec:
  type: NodePort
  ports:
    - port: 5044
      targetPort: 5044
      nodePort: 32002
  selector:
    app: filebeat
